option(STELNET_AUDIO_BUILD_SERVER_FRONTENDS
    "Build optional in-process lucy_audio_server frontend adapters"
    OFF)
set(STELNET_AUDIO_SERVER_FRONTEND_MODULES ""
    CACHE STRING "Semicolon-separated optional lucy_audio_server frontend modules to build")
set(STELNET_AUDIO_SERVER_FRONTENDS_DIR ""
    CACHE PATH "Optional external server frontend module package")

if (NOT STELNET_AUDIO_BUILD_SERVER_FRONTENDS AND STELNET_AUDIO_SERVER_FRONTEND_MODULES)
    message(FATAL_ERROR
        "STELNET_AUDIO_SERVER_FRONTEND_MODULES requires STELNET_AUDIO_BUILD_SERVER_FRONTENDS=ON")
endif()

function(lucy_audio_register_server_frontend STELNET_AUDIO_SERVER_FRONTEND_NAME)
    set(options)
    set(one_value_args REGISTER_FUNCTION)
    set(multi_value_args SOURCES INCLUDE_DIRS LIBRARIES COMPILE_DEFINITIONS)
    cmake_parse_arguments(
        STELNET_AUDIO_REGISTERED_FRONTEND
        "${options}"
        "${one_value_args}"
        "${multi_value_args}"
        ${ARGN})

    set_property(GLOBAL APPEND PROPERTY
        "STELNET_AUDIO_SERVER_FRONTEND_REGISTERED_MODULES"
        "${STELNET_AUDIO_SERVER_FRONTEND_NAME}")
    set_property(GLOBAL PROPERTY
        "STELNET_AUDIO_SERVER_FRONTEND_${STELNET_AUDIO_SERVER_FRONTEND_NAME}_REGISTER_FUNCTION"
        "${STELNET_AUDIO_REGISTERED_FRONTEND_REGISTER_FUNCTION}")
    set_property(GLOBAL PROPERTY
        "STELNET_AUDIO_SERVER_FRONTEND_${STELNET_AUDIO_SERVER_FRONTEND_NAME}_SOURCES"
        "${STELNET_AUDIO_REGISTERED_FRONTEND_SOURCES}")
    set_property(GLOBAL PROPERTY
        "STELNET_AUDIO_SERVER_FRONTEND_${STELNET_AUDIO_SERVER_FRONTEND_NAME}_INCLUDE_DIRS"
        "${STELNET_AUDIO_REGISTERED_FRONTEND_INCLUDE_DIRS}")
    set_property(GLOBAL PROPERTY
        "STELNET_AUDIO_SERVER_FRONTEND_${STELNET_AUDIO_SERVER_FRONTEND_NAME}_LIBRARIES"
        "${STELNET_AUDIO_REGISTERED_FRONTEND_LIBRARIES}")
    set_property(GLOBAL PROPERTY
        "STELNET_AUDIO_SERVER_FRONTEND_${STELNET_AUDIO_SERVER_FRONTEND_NAME}_COMPILE_DEFINITIONS"
        "${STELNET_AUDIO_REGISTERED_FRONTEND_COMPILE_DEFINITIONS}")
endfunction()

function(lucy_audio_collect_server_frontends)
    get_property(STELNET_AUDIO_SERVER_FRONTENDS_ALREADY_COLLECTED GLOBAL PROPERTY
        "STELNET_AUDIO_SERVER_FRONTENDS_COLLECTED" SET)
    if (STELNET_AUDIO_SERVER_FRONTENDS_ALREADY_COLLECTED)
        return()
    endif()
    set_property(GLOBAL PROPERTY "STELNET_AUDIO_SERVER_FRONTENDS_COLLECTED" TRUE)

    set(STELNET_AUDIO_SERVER_FRONTEND_DECLARATIONS "")
    set(STELNET_AUDIO_SERVER_FRONTEND_REGISTRATIONS "")
    set(STELNET_AUDIO_SERVER_FRONTEND_SOURCES "")
    set(STELNET_AUDIO_SERVER_FRONTEND_INCLUDE_DIRS "")
    set(STELNET_AUDIO_SERVER_FRONTEND_LIBRARIES "")
    set(STELNET_AUDIO_SERVER_FRONTEND_COMPILE_DEFINITIONS "")

    if (STELNET_AUDIO_BUILD_SERVER_FRONTENDS AND STELNET_AUDIO_SERVER_FRONTEND_MODULES)
        if (NOT STELNET_AUDIO_SERVER_FRONTENDS_DIR)
            message(FATAL_ERROR
                "STELNET_AUDIO_BUILD_SERVER_FRONTENDS=ON requires STELNET_AUDIO_SERVER_FRONTENDS_DIR=<external frontend package>")
        endif()
        get_filename_component(
            STELNET_AUDIO_SERVER_FRONTENDS_DIR_ABS
            "${STELNET_AUDIO_SERVER_FRONTENDS_DIR}"
            ABSOLUTE
            BASE_DIR "${PROJECT_SOURCE_DIR}")
        if (NOT EXISTS "${STELNET_AUDIO_SERVER_FRONTENDS_DIR_ABS}/server_frontends.cmake")
            message(FATAL_ERROR
                "STELNET_AUDIO_SERVER_FRONTENDS_DIR must contain server_frontends.cmake: ${STELNET_AUDIO_SERVER_FRONTENDS_DIR_ABS}")
        endif()

        set_property(GLOBAL PROPERTY "STELNET_AUDIO_SERVER_FRONTEND_REGISTERED_MODULES" "")
        include("${STELNET_AUDIO_SERVER_FRONTENDS_DIR_ABS}/server_frontends.cmake")
        get_property(STELNET_AUDIO_REGISTERED_SERVER_FRONTENDS GLOBAL PROPERTY
            "STELNET_AUDIO_SERVER_FRONTEND_REGISTERED_MODULES")

        foreach(STELNET_AUDIO_SERVER_FRONTEND_MODULE IN LISTS STELNET_AUDIO_SERVER_FRONTEND_MODULES)
            list(FIND STELNET_AUDIO_REGISTERED_SERVER_FRONTENDS "${STELNET_AUDIO_SERVER_FRONTEND_MODULE}" STELNET_AUDIO_SERVER_FRONTEND_INDEX)
            if (STELNET_AUDIO_SERVER_FRONTEND_INDEX EQUAL -1)
                message(FATAL_ERROR
                    "External server frontend package did not register requested module: ${STELNET_AUDIO_SERVER_FRONTEND_MODULE}")
            endif()

            get_property(STELNET_AUDIO_FRONTEND_REGISTER_FUNCTION GLOBAL PROPERTY
                "STELNET_AUDIO_SERVER_FRONTEND_${STELNET_AUDIO_SERVER_FRONTEND_MODULE}_REGISTER_FUNCTION")
            get_property(STELNET_AUDIO_FRONTEND_SOURCES GLOBAL PROPERTY
                "STELNET_AUDIO_SERVER_FRONTEND_${STELNET_AUDIO_SERVER_FRONTEND_MODULE}_SOURCES")
            get_property(STELNET_AUDIO_FRONTEND_INCLUDE_DIRS GLOBAL PROPERTY
                "STELNET_AUDIO_SERVER_FRONTEND_${STELNET_AUDIO_SERVER_FRONTEND_MODULE}_INCLUDE_DIRS")
            get_property(STELNET_AUDIO_FRONTEND_LIBRARIES GLOBAL PROPERTY
                "STELNET_AUDIO_SERVER_FRONTEND_${STELNET_AUDIO_SERVER_FRONTEND_MODULE}_LIBRARIES")
            get_property(STELNET_AUDIO_FRONTEND_COMPILE_DEFINITIONS GLOBAL PROPERTY
                "STELNET_AUDIO_SERVER_FRONTEND_${STELNET_AUDIO_SERVER_FRONTEND_MODULE}_COMPILE_DEFINITIONS")

            if (STELNET_AUDIO_FRONTEND_REGISTER_FUNCTION)
                string(APPEND STELNET_AUDIO_SERVER_FRONTEND_DECLARATIONS
                    "void ${STELNET_AUDIO_FRONTEND_REGISTER_FUNCTION}(ServerFrontendRegistry & registry);\n")
                string(APPEND STELNET_AUDIO_SERVER_FRONTEND_REGISTRATIONS
                    "    ${STELNET_AUDIO_FRONTEND_REGISTER_FUNCTION}(registry);\n")
            endif()
            list(APPEND STELNET_AUDIO_SERVER_FRONTEND_SOURCES ${STELNET_AUDIO_FRONTEND_SOURCES})
            list(APPEND STELNET_AUDIO_SERVER_FRONTEND_INCLUDE_DIRS ${STELNET_AUDIO_FRONTEND_INCLUDE_DIRS})
            list(APPEND STELNET_AUDIO_SERVER_FRONTEND_LIBRARIES ${STELNET_AUDIO_FRONTEND_LIBRARIES})
            list(APPEND STELNET_AUDIO_SERVER_FRONTEND_COMPILE_DEFINITIONS ${STELNET_AUDIO_FRONTEND_COMPILE_DEFINITIONS})
        endforeach()
    endif()

    if (STELNET_AUDIO_SERVER_FRONTEND_SOURCES)
        list(REMOVE_DUPLICATES STELNET_AUDIO_SERVER_FRONTEND_INCLUDE_DIRS)
        list(REMOVE_DUPLICATES STELNET_AUDIO_SERVER_FRONTEND_LIBRARIES)
        list(REMOVE_DUPLICATES STELNET_AUDIO_SERVER_FRONTEND_COMPILE_DEFINITIONS)
    endif()

    set_property(GLOBAL PROPERTY
        "STELNET_AUDIO_SERVER_FRONTEND_SELECTED_DECLARATIONS"
        "${STELNET_AUDIO_SERVER_FRONTEND_DECLARATIONS}")
    set_property(GLOBAL PROPERTY
        "STELNET_AUDIO_SERVER_FRONTEND_SELECTED_REGISTRATIONS"
        "${STELNET_AUDIO_SERVER_FRONTEND_REGISTRATIONS}")
    set_property(GLOBAL PROPERTY
        "STELNET_AUDIO_SERVER_FRONTEND_SELECTED_SOURCES"
        "${STELNET_AUDIO_SERVER_FRONTEND_SOURCES}")
    set_property(GLOBAL PROPERTY
        "STELNET_AUDIO_SERVER_FRONTEND_SELECTED_INCLUDE_DIRS"
        "${STELNET_AUDIO_SERVER_FRONTEND_INCLUDE_DIRS}")
    set_property(GLOBAL PROPERTY
        "STELNET_AUDIO_SERVER_FRONTEND_SELECTED_LIBRARIES"
        "${STELNET_AUDIO_SERVER_FRONTEND_LIBRARIES}")
    set_property(GLOBAL PROPERTY
        "STELNET_AUDIO_SERVER_FRONTEND_SELECTED_COMPILE_DEFINITIONS"
        "${STELNET_AUDIO_SERVER_FRONTEND_COMPILE_DEFINITIONS}")
endfunction()

function(lucy_audio_configure_server_frontends STELNET_AUDIO_SERVER_TARGET)
    lucy_audio_collect_server_frontends()

    get_property(STELNET_AUDIO_SERVER_FRONTEND_DECLARATIONS GLOBAL PROPERTY
        "STELNET_AUDIO_SERVER_FRONTEND_SELECTED_DECLARATIONS")
    get_property(STELNET_AUDIO_SERVER_FRONTEND_REGISTRATIONS GLOBAL PROPERTY
        "STELNET_AUDIO_SERVER_FRONTEND_SELECTED_REGISTRATIONS")
    get_property(STELNET_AUDIO_SERVER_FRONTEND_SOURCES GLOBAL PROPERTY
        "STELNET_AUDIO_SERVER_FRONTEND_SELECTED_SOURCES")
    get_property(STELNET_AUDIO_SERVER_FRONTEND_INCLUDE_DIRS GLOBAL PROPERTY
        "STELNET_AUDIO_SERVER_FRONTEND_SELECTED_INCLUDE_DIRS")
    get_property(STELNET_AUDIO_SERVER_FRONTEND_LIBRARIES GLOBAL PROPERTY
        "STELNET_AUDIO_SERVER_FRONTEND_SELECTED_LIBRARIES")
    get_property(STELNET_AUDIO_SERVER_FRONTEND_COMPILE_DEFINITIONS GLOBAL PROPERTY
        "STELNET_AUDIO_SERVER_FRONTEND_SELECTED_COMPILE_DEFINITIONS")

    file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/generated")

    if (STELNET_AUDIO_SERVER_FRONTEND_SOURCES)
        add_library(lucy_audio_server_frontends OBJECT
            ${STELNET_AUDIO_SERVER_FRONTEND_SOURCES}
        )
        target_include_directories(lucy_audio_server_frontends PRIVATE
            "${PROJECT_SOURCE_DIR}/app/server"
            ${STELNET_AUDIO_SERVER_FRONTEND_INCLUDE_DIRS}
        )
        target_link_libraries(lucy_audio_server_frontends PUBLIC engine_runtime PRIVATE
            ${STELNET_AUDIO_SERVER_FRONTEND_LIBRARIES})
        target_compile_definitions(lucy_audio_server_frontends PRIVATE
            ${STELNET_AUDIO_SERVER_FRONTEND_COMPILE_DEFINITIONS})
        target_sources(${STELNET_AUDIO_SERVER_TARGET} PRIVATE $<TARGET_OBJECTS:lucy_audio_server_frontends>)
        target_link_libraries(${STELNET_AUDIO_SERVER_TARGET} PRIVATE
            lucy_audio_server_frontends
            ${STELNET_AUDIO_SERVER_FRONTEND_LIBRARIES})
        target_compile_definitions(${STELNET_AUDIO_SERVER_TARGET} PRIVATE
            ${STELNET_AUDIO_SERVER_FRONTEND_COMPILE_DEFINITIONS})
    endif()

    file(WRITE
        "${CMAKE_CURRENT_BINARY_DIR}/generated/server_frontend_module_declarations.inc"
        "${STELNET_AUDIO_SERVER_FRONTEND_DECLARATIONS}")
    file(WRITE
        "${CMAKE_CURRENT_BINARY_DIR}/generated/server_frontend_module_registrations.inc"
        "${STELNET_AUDIO_SERVER_FRONTEND_REGISTRATIONS}")
endfunction()
